// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AdminMutation struct {
	UpdateUserRoles          *User           `json:"updateUserRoles"`
	CreateMasterDataItem     *MasterDataItem `json:"createMasterDataItem"`
	UpdateMasterDataItem     *MasterDataItem `json:"updateMasterDataItem"`
	DeactivateMasterDataItem *MasterDataItem `json:"deactivateMasterDataItem"`
}

// ส่วนของผู้ดูแลระบบ
//
// ⚠️ ทุก field ในนี้ nullable โดยตั้งใจ — ดูหัวข้อ "partial error" ท้ายไฟล์
type AdminQuery struct {
	Users  *UserConnection   `json:"users,omitempty"`
	Pets   *PetConnection    `json:"pets,omitempty"`
	Events *EventConnection  `json:"events,omitempty"`
	Roles  []*RoleDefinition `json:"roles,omitempty"`
}

type Event struct {
	ID            string    `json:"id"`
	Timestamp     time.Time `json:"timestamp"`
	EventType     string    `json:"eventType"`
	Action        string    `json:"action"`
	ActorID       *string   `json:"actorId,omitempty"`
	ActorUsername *string   `json:"actorUsername,omitempty"`
	EntityType    *string   `json:"entityType,omitempty"`
	EntityID      *string   `json:"entityId,omitempty"`
	Payload       JSON      `json:"payload,omitempty"`
	// สัตว์เลี้ยงที่ event นี้อ้างถึง — resolve ให้เมื่อ entityType = "Pet"
	//
	// ทำให้หน้า Event Log ไม่ต้องดึง pets ทั้งหมดมาจับคู่ชื่อเองแบบทุกวันนี้
	Pet *Pet `json:"pet,omitempty"`
}

type EventConnection struct {
	Edges      []*EventEdge `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount *int         `json:"totalCount,omitempty"`
}

type EventEdge struct {
	Cursor string `json:"cursor"`
	Node   *Event `json:"node"`
}

type LitterDailyBucket struct {
	Date time.Time `json:"date"`
	Poop int       `json:"poop"`
	Pee  int       `json:"pee"`
}

type LitterLog struct {
	ID                string    `json:"id"`
	PetID             string    `json:"petId"`
	Date              time.Time `json:"date"`
	Type              string    `json:"type"`
	Amount            int       `json:"amount"`
	CreatedByUsername *string   `json:"createdByUsername,omitempty"`
	CreatedAt         time.Time `json:"createdAt"`
}

type LitterLogConnection struct {
	Edges      []*LitterLogEdge `json:"edges"`
	PageInfo   *PageInfo        `json:"pageInfo"`
	TotalCount *int             `json:"totalCount,omitempty"`
}

type LitterLogEdge struct {
	Cursor string     `json:"cursor"`
	Node   *LitterLog `json:"node"`
}

// id ให้ client กำหนดเองได้ตามที่ REST เดิมทำ
//
// เพื่อให้แอปสร้าง log ตอนออฟไลน์แล้วส่งซ้ำได้โดยไม่เกิดรายการซ้ำ
// ส่ง id เดิมของสัตว์เลี้ยงตัวเดิม = idempotent
// ส่ง id ที่เป็นของสัตว์เลี้ยงตัวอื่น = error LOG_ID_CONFLICT
type LitterLogInput struct {
	ID     *string    `json:"id,omitempty"`
	Date   *time.Time `json:"date,omitempty"`
	Type   string     `json:"type"`
	Amount int        `json:"amount"`
}

type LitterSummary struct {
	From          time.Time `json:"from"`
	To            time.Time `json:"to"`
	TotalPoop     int       `json:"totalPoop"`
	TotalPee      int       `json:"totalPee"`
	AvgPoopPerDay float64   `json:"avgPoopPerDay"`
	AvgPeePerDay  float64   `json:"avgPeePerDay"`
	// ครบทุกวันในช่วง วันที่ไม่มีข้อมูลจะเป็น 0 เพื่อให้กราฟไม่ขาดช่วง
	Daily []*LitterDailyBucket `json:"daily"`
}

type MasterDataInput struct {
	Code        string  `json:"code"`
	NameEn      string  `json:"nameEn"`
	NameTh      *string `json:"nameTh,omitempty"`
	SpeciesCode *string `json:"speciesCode,omitempty"`
	SortOrder   int     `json:"sortOrder"`
	IsActive    *bool   `json:"isActive,omitempty"`
}

type MasterDataItem struct {
	Code        string    `json:"code"`
	NameEn      string    `json:"nameEn"`
	NameTh      *string   `json:"nameTh,omitempty"`
	Label       string    `json:"label"`
	SpeciesCode *string   `json:"speciesCode,omitempty"`
	SortOrder   int       `json:"sortOrder"`
	IsActive    bool      `json:"isActive"`
	Version     int       `json:"version"`
	UpdatedAt   time.Time `json:"updatedAt"`
	UpdatedBy   *string   `json:"updatedBy,omitempty"`
}

// version บังคับส่งเสมอ เป็น optimistic locking ของเดิม
//
// ถ้าไม่ตรงกับค่าใน database จะได้ error VERSION_CONFLICT
// กัน admin สองคนแก้ทับกันโดยไม่รู้ตัว
type MasterDataUpdateInput struct {
	NameEn      string  `json:"nameEn"`
	NameTh      *string `json:"nameTh,omitempty"`
	SpeciesCode *string `json:"speciesCode,omitempty"`
	SortOrder   int     `json:"sortOrder"`
	IsActive    *bool   `json:"isActive,omitempty"`
	Version     int     `json:"version"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Pet struct {
	ID               string    `json:"id"`
	Name             string    `json:"name"`
	Species          string    `json:"species"`
	Breed            string    `json:"breed"`
	ColorCode        string    `json:"colorCode"`
	BirthDate        time.Time `json:"birthDate"`
	Gender           string    `json:"gender"`
	CurrentWeight    *float64  `json:"currentWeight,omitempty"`
	MicrochipID      *string   `json:"microchipId,omitempty"`
	IsSpayedNeutered bool      `json:"isSpayedNeutered"`
	BloodType        *string   `json:"bloodType,omitempty"`
	Allergies        *string   `json:"allergies,omitempty"`
	Personality      *string   `json:"personality,omitempty"`
	// อายุแบบอ่านง่าย เช่น "2 ปี 5 เดือน"
	//
	// ตอนนี้ client คำนวณเองจาก birthDate ทั้ง iOS และ back office
	// ย้ายมาคำนวณที่เดียวเพื่อให้ทุกที่แสดงตรงกัน
	AgeLabel string `json:"ageLabel"`
	Owner    *User  `json:"owner"`
	// ผู้ดูแลร่วม พร้อมข้อมูล user ที่ resolve ให้แล้ว
	Caregivers []*PetCaregiver `json:"caregivers"`
	// สิทธิ์ของผู้เรียกคนนี้ต่อสัตว์เลี้ยงตัวนี้
	//
	// ตอนนี้ iOS คำนวณเองด้วยการเทียบ UUID เป็น string ตัวพิมพ์เล็ก
	// และเขียนซ้ำอยู่สองที่ ซึ่งเป็นตรรกะเรื่องสิทธิ์ที่ไม่ควรอยู่ฝั่ง client
	ViewerPermissions *PetViewerPermissions `json:"viewerPermissions"`
	HasAvatar         bool                  `json:"hasAvatar"`
	// URL ของรูป ชี้ไปที่ REST endpoint เดิมที่มี ETag อยู่แล้ว
	//
	// ห้ามใส่ตัวรูปเป็น base64 ลงใน GraphQL — ปัจจุบัน GET /pets ส่ง avatarData
	// มาด้วย ทำให้ผู้ใช้ที่มีแมว 3 ตัวโหลดเกือบ 4MB ทุกครั้งที่เปิดหน้ารายการ
	AvatarURL  *string              `json:"avatarUrl,omitempty"`
	LitterLogs *LitterLogConnection `json:"litterLogs"`
	WaterLogs  *WaterLogConnection  `json:"waterLogs"`
	// สรุปรายวันสำหรับหน้า Analytics
	//
	// ตอนนี้ client ดึง log ทั้งหมดตั้งแต่ต้นแล้ว group เองในเครื่อง
	// ซึ่งทั้งเปลืองและทำงานไม่ถูกต้อง (ดูหมายเหตุใน VT-98)
	// ให้ฝั่ง server ทำ GROUP BY ให้จบ
	LitterSummary *LitterSummary `json:"litterSummary"`
	WaterSummary  *WaterSummary  `json:"waterSummary"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
}

type PetCaregiver struct {
	ID    string `json:"id"`
	PetID string `json:"petId"`
	// ผู้ใช้ที่เป็นผู้ดูแล — resolve ผ่าน dataloader
	//
	// แก้ปัญหาที่ทั้ง iOS และ back office ดึงตาราง user ทั้งระบบมาทำ map
	// เพื่อแปลง id เป็นชื่อ ซึ่งทำให้อีเมลของทุกคนหลุดไปอยู่ที่เครื่อง client
	User        *User            `json:"user"`
	Permissions []*PetPermission `json:"permissions"`
	CreatedAt   time.Time        `json:"createdAt"`
	UpdatedAt   time.Time        `json:"updatedAt"`
}

type PetConnection struct {
	Edges      []*PetEdge `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount *int       `json:"totalCount,omitempty"`
}

type PetEdge struct {
	Cursor string `json:"cursor"`
	Node   *Pet   `json:"node"`
}

type PetInput struct {
	Name             string    `json:"name"`
	Species          string    `json:"species"`
	Breed            string    `json:"breed"`
	ColorCode        string    `json:"colorCode"`
	BirthDate        time.Time `json:"birthDate"`
	Gender           string    `json:"gender"`
	CurrentWeight    *float64  `json:"currentWeight,omitempty"`
	MicrochipID      *string   `json:"microchipId,omitempty"`
	IsSpayedNeutered bool      `json:"isSpayedNeutered"`
	BloodType        *string   `json:"bloodType,omitempty"`
	Allergies        *string   `json:"allergies,omitempty"`
	Personality      *string   `json:"personality,omitempty"`
}

type PetPermission struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IsActive    bool   `json:"isActive"`
}

type PetViewerPermissions struct {
	IsOwner             bool `json:"isOwner"`
	CanEditProfile      bool `json:"canEditProfile"`
	CanManageCaregivers bool `json:"canManageCaregivers"`
	CanManageLitter     bool `json:"canManageLitter"`
	CanManageWater      bool `json:"canManageWater"`
	CanDelete           bool `json:"canDelete"`
}

type Query struct {
}

type RoleDefinition struct {
	Code        Role   `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IsSystem    bool   `json:"isSystem"`
}

type User struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	FullName      string `json:"fullName"`
	EmailVerified bool   `json:"emailVerified"`
	// role ของผู้ใช้คนนี้ — null ถ้าผู้เรียกไม่มีสิทธิ์เห็น
	//
	// ผู้ใช้ทั่วไปเห็นได้เฉพาะ role ของตัวเอง ส่วน SUPER_ADMIN เห็นได้ทุกคน
	// ไม่ทำเป็น non-null เพราะจะบังคับให้ต้องเปิดข้อมูลนี้ให้ทุกคน
	Roles []Role `json:"roles,omitempty"`
}

type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount *int        `json:"totalCount,omitempty"`
}

type UserEdge struct {
	Cursor string `json:"cursor"`
	Node   *User  `json:"node"`
}

type Viewer struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	FullName      string `json:"fullName"`
	EmailVerified bool   `json:"emailVerified"`
	Roles         []Role `json:"roles"`
	// สัตว์เลี้ยงทั้งหมดที่ผู้ใช้คนนี้เข้าถึงได้ (เป็นเจ้าของหรือเป็นผู้ดูแล)
	Pets []*Pet `json:"pets"`
	// จำนวนสัตว์เลี้ยง — มีไว้เพื่อหน้า Home โดยเฉพาะ
	//
	// หน้า Home ต้องการแค่ตัวเลขนี้กับชื่อ ถ้าไม่มี field นี้จะต้องดึง pets
	// ทั้งก้อนมานับเอง ซึ่งเป็นสาเหตุที่หน้า Home ปัจจุบันโหลดรูปแมวทุกตัว
	// ทั้งที่แสดงแค่ตัวเลขเดียว
	PetCount int `json:"petCount"`
}

type WaterDailyBucket struct {
	Date time.Time `json:"date"`
	Ml   int       `json:"ml"`
}

type WaterLog struct {
	ID                string    `json:"id"`
	PetID             string    `json:"petId"`
	Date              time.Time `json:"date"`
	Amount            int       `json:"amount"`
	CreatedByUsername *string   `json:"createdByUsername,omitempty"`
	CreatedAt         time.Time `json:"createdAt"`
}

type WaterLogConnection struct {
	Edges      []*WaterLogEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount *int            `json:"totalCount,omitempty"`
}

type WaterLogEdge struct {
	Cursor string    `json:"cursor"`
	Node   *WaterLog `json:"node"`
}

type WaterLogInput struct {
	ID     *string    `json:"id,omitempty"`
	Date   *time.Time `json:"date,omitempty"`
	Amount int        `json:"amount"`
}

type WaterSummary struct {
	From        time.Time `json:"from"`
	To          time.Time `json:"to"`
	TotalMl     int       `json:"totalMl"`
	AvgMlPerDay float64   `json:"avgMlPerDay"`
	// เป้าหมายต่อวันคำนวณจากน้ำหนัก (50 ml ต่อกิโลกรัม)
	//
	// null เมื่อสัตว์เลี้ยงยังไม่มีน้ำหนักบันทึกไว้ — client ปัจจุบันเดาเป็น 4 กก.
	// แล้วแสดงเป้าหมายที่ไม่จริง ซึ่งแย่กว่าการบอกว่าไม่รู้
	DailyTargetMl *int                `json:"dailyTargetMl,omitempty"`
	Daily         []*WaterDailyBucket `json:"daily"`
}

type MasterDataType string

const (
	MasterDataTypeSpecies     MasterDataType = "SPECIES"
	MasterDataTypeCatBreeds   MasterDataType = "CAT_BREEDS"
	MasterDataTypeBloodTypes  MasterDataType = "BLOOD_TYPES"
	MasterDataTypeLitterTypes MasterDataType = "LITTER_TYPES"
	MasterDataTypeGenders     MasterDataType = "GENDERS"
)

var AllMasterDataType = []MasterDataType{
	MasterDataTypeSpecies,
	MasterDataTypeCatBreeds,
	MasterDataTypeBloodTypes,
	MasterDataTypeLitterTypes,
	MasterDataTypeGenders,
}

func (e MasterDataType) IsValid() bool {
	switch e {
	case MasterDataTypeSpecies, MasterDataTypeCatBreeds, MasterDataTypeBloodTypes, MasterDataTypeLitterTypes, MasterDataTypeGenders:
		return true
	}
	return false
}

func (e MasterDataType) String() string {
	return string(e)
}

func (e *MasterDataType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MasterDataType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MasterDataType", str)
	}
	return nil
}

func (e MasterDataType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MasterDataType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MasterDataType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleSuperAdmin Role = "SUPER_ADMIN"
	RolePetAdmin   Role = "PET_ADMIN"
	RoleUser       Role = "USER"
)

var AllRole = []Role{
	RoleSuperAdmin,
	RolePetAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleSuperAdmin, RolePetAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
