package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vertex/bff/internal/client"
	"github.com/vertex/bff/internal/graph/model"
	"github.com/vertex/bff/internal/loader"
)

// UpdateUserRoles is the resolver for the updateUserRoles field.
func (r *adminMutationResolver) UpdateUserRoles(ctx context.Context, obj *model.AdminMutation, userID string, roles []model.Role) (*model.User, error) {
	codes := make([]string, 0, len(roles))
	for _, role := range roles {
		codes = append(codes, string(role))
	}
	u, err := r.AuthSvc.AdminUpdateRoles(ctx, userID, codes)
	if err != nil {
		return nil, gqlErr(err)
	}
	return toUser(*u), nil
}

// CreateMasterDataItem is the resolver for the createMasterDataItem field.
func (r *adminMutationResolver) CreateMasterDataItem(ctx context.Context, obj *model.AdminMutation, typeArg model.MasterDataType, input model.MasterDataInput) (*model.MasterDataItem, error) {
	body := map[string]any{
		"code": input.Code, "nameEn": input.NameEn, "nameTh": input.NameTh,
		"speciesCode": input.SpeciesCode, "sortOrder": input.SortOrder, "isActive": input.IsActive,
	}
	item, err := r.PetSvc.AdminCreateMasterData(ctx, masterDataPath(typeArg), body)
	if err != nil {
		return nil, gqlErr(err)
	}
	return toMasterDataItem(*item), nil
}

// UpdateMasterDataItem is the resolver for the updateMasterDataItem field.
func (r *adminMutationResolver) UpdateMasterDataItem(ctx context.Context, obj *model.AdminMutation, typeArg model.MasterDataType, code string, input model.MasterDataUpdateInput) (*model.MasterDataItem, error) {
	body := map[string]any{
		"nameEn": input.NameEn, "nameTh": input.NameTh, "speciesCode": input.SpeciesCode,
		"sortOrder": input.SortOrder, "isActive": input.IsActive,
		// version ต้องส่งเสมอ เป็น optimistic locking ของเดิม
		// ถ้าไม่ตรงจะได้ 409 แล้วแปลงเป็น code CONFLICT
		"version": input.Version,
	}
	item, err := r.PetSvc.AdminUpdateMasterData(ctx, masterDataPath(typeArg), code, body)
	if err != nil {
		return nil, gqlErr(err)
	}
	return toMasterDataItem(*item), nil
}

// DeactivateMasterDataItem is the resolver for the deactivateMasterDataItem field.
func (r *adminMutationResolver) DeactivateMasterDataItem(ctx context.Context, obj *model.AdminMutation, typeArg model.MasterDataType, code string) (*model.MasterDataItem, error) {
	path := masterDataPath(typeArg)
	if err := r.PetSvc.AdminDeactivateMasterData(ctx, path, code); err != nil {
		return nil, gqlErr(err)
	}
	// REST ตอบแค่สรุปการปิดใช้งาน ไม่ได้คืนตัวรายการมาให้
	// จึงต้องอ่านกลับมาเพื่อคืนสถานะล่าสุดตามที่ schema สัญญาไว้
	items, err := r.PetSvc.AdminListMasterData(ctx, path)
	if err != nil {
		return nil, gqlErr(err)
	}
	for _, it := range items {
		if it.Code == code {
			return toMasterDataItem(it), nil
		}
	}
	return nil, &gqlerror.Error{
		Message:    "ปิดการใช้งานแล้วแต่อ่านค่ากลับมาไม่ได้",
		Extensions: map[string]any{"code": "NOT_FOUND"},
	}
}

// Users is the resolver for the users field.
func (r *adminQueryResolver) Users(ctx context.Context, obj *model.AdminQuery, first *int, after *string, search *string) (*model.UserConnection, error) {
	q := ""
	if search != nil {
		q = *search
	}
	users, err := r.AuthSvc.AdminListUsers(ctx, q)
	if err != nil {
		return nil, gqlErr(err)
	}

	// REST ยังไม่แบ่งหน้า (ตัดที่ 200 แถวตายตัว) จึงต้องแบ่งเองที่นี่
	// เมื่อ auth-service รองรับ offset แล้วให้ย้ายไปทำที่นั่นแทน
	offset, err := decodeOffset(after)
	if err != nil {
		return nil, badRequest(err.Error())
	}
	size := pageSize(first)

	total := len(users)
	end := offset + size
	if end > total {
		end = total
	}
	var page []client.User
	if offset < total {
		page = users[offset:end]
	}

	edges := make([]*model.UserEdge, 0, len(page))
	for i, u := range page {
		edges = append(edges, &model.UserEdge{Cursor: encodeOffset(offset + i + 1), Node: toUser(u)})
	}
	totalCount := total
	return &model.UserConnection{
		Edges:      edges,
		PageInfo:   pageInfoFor(edges != nil && end < total, lastCursor(edges)),
		TotalCount: &totalCount,
	}, nil
}

// Pets is the resolver for the pets field.
func (r *adminQueryResolver) Pets(ctx context.Context, obj *model.AdminQuery, first *int, after *string) (*model.PetConnection, error) {
	pets, err := r.PetSvc.AdminListPets(ctx)
	if err != nil {
		return nil, gqlErr(err)
	}
	offset, err := decodeOffset(after)
	if err != nil {
		return nil, badRequest(err.Error())
	}
	size := pageSize(first)

	total := len(pets)
	end := offset + size
	if end > total {
		end = total
	}
	var page []client.Pet
	if offset < total {
		page = pets[offset:end]
	}

	edges := make([]*model.PetEdge, 0, len(page))
	for i, p := range page {
		edges = append(edges, &model.PetEdge{Cursor: encodeOffset(offset + i + 1), Node: r.petModel(ctx, p)})
	}
	totalCount := total
	return &model.PetConnection{
		Edges:      edges,
		PageInfo:   pageInfoFor(end < total, lastPetCursor(edges)),
		TotalCount: &totalCount,
	}, nil
}

// Events is the resolver for the events field.
func (r *adminQueryResolver) Events(ctx context.Context, obj *model.AdminQuery, first *int, after *string, entityType *string, entityID *string, actorID *string) (*model.EventConnection, error) {
	offset, err := decodeOffset(after)
	if err != nil {
		return nil, badRequest(err.Error())
	}
	size := pageSize(first)

	f := client.EventFilter{Limit: size, Offset: offset}
	if entityType != nil {
		f.EntityType = *entityType
	}
	if entityID != nil {
		f.EntityID = *entityID
	}
	if actorID != nil {
		f.ActorID = *actorID
	}

	page, err := r.EventSvc.AdminListEvents(ctx, f)
	if err != nil {
		return nil, gqlErr(err)
	}

	edges := make([]*model.EventEdge, 0, len(page.Data))
	for i, e := range page.Data {
		edges = append(edges, &model.EventEdge{Cursor: encodeOffset(offset + i + 1), Node: toEvent(e)})
	}
	total := int(page.Total)
	return &model.EventConnection{
		Edges:      edges,
		PageInfo:   pageInfoFor(offset+len(page.Data) < total, lastEventCursor(edges)),
		TotalCount: &total,
	}, nil
}

// Roles is the resolver for the roles field.
func (r *adminQueryResolver) Roles(ctx context.Context, obj *model.AdminQuery) ([]*model.RoleDefinition, error) {
	roles, err := r.AuthSvc.AdminListRoles(ctx)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*model.RoleDefinition, 0, len(roles))
	for _, rd := range roles {
		role := model.Role(rd.Code)
		if !role.IsValid() {
			continue
		}
		out = append(out, &model.RoleDefinition{
			Code: role, Name: rd.Name, Description: rd.Description, IsSystem: rd.IsSystem,
		})
	}
	return out, nil
}

// Pet is the resolver for the pet field.
func (r *eventResolver) Pet(ctx context.Context, obj *model.Event) (*model.Pet, error) {
	// event ผูกกับ entity อื่นด้วยคู่ string ไม่ใช่ foreign key
	// จึงต้องเช็คชนิดก่อน ไม่งั้นจะเอา id ของอย่างอื่นไปถามหาสัตว์เลี้ยง
	if obj.EntityType == nil || *obj.EntityType != "Pet" || obj.EntityID == nil || *obj.EntityID == "" {
		return nil, nil
	}
	l := loader.From(ctx)
	if l == nil {
		return nil, nil
	}
	p, ok := l.Pet(ctx, *obj.EntityID)
	if !ok {
		// สัตว์เลี้ยงถูกลบไปแล้วแต่ event ยังอยู่ — เป็นเรื่องปกติของ log
		// คืน null ดีกว่าทำให้ทั้งแถวหาย
		return nil, nil
	}
	return r.petModel(ctx, p), nil
}

// CreatePet is the resolver for the createPet field.
func (r *mutationResolver) CreatePet(ctx context.Context, input model.PetInput) (*model.Pet, error) {
	p, err := r.PetSvc.CreatePet(ctx, petInputBody(input))
	if err != nil {
		return nil, gqlErr(err)
	}
	return r.petModel(ctx, *p), nil
}

// UpdatePet is the resolver for the updatePet field.
func (r *mutationResolver) UpdatePet(ctx context.Context, id string, input model.PetInput) (*model.Pet, error) {
	p, err := r.PetSvc.UpdatePet(ctx, id, petInputBody(input))
	if err != nil {
		return nil, gqlErr(err)
	}
	return r.petModel(ctx, *p), nil
}

// DeletePet is the resolver for the deletePet field.
func (r *mutationResolver) DeletePet(ctx context.Context, id string) (bool, error) {
	if err := r.PetSvc.DeletePet(ctx, id); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// AddCaregiver is the resolver for the addCaregiver field.
func (r *mutationResolver) AddCaregiver(ctx context.Context, petID string, userID string) (*model.PetCaregiver, error) {
	c, err := r.PetSvc.AddCaregiver(ctx, petID, userID)
	if err != nil {
		return nil, gqlErr(err)
	}
	return caregiverWithUser(*c), nil
}

// UpdateCaregiverPermissions is the resolver for the updateCaregiverPermissions field.
func (r *mutationResolver) UpdateCaregiverPermissions(ctx context.Context, petID string, caregiverID string, permissionIds []string) (*model.PetCaregiver, error) {
	c, err := r.PetSvc.UpdateCaregiverPermissions(ctx, petID, caregiverID, permissionIds)
	if err != nil {
		return nil, gqlErr(err)
	}
	return caregiverWithUser(*c), nil
}

// RemoveCaregiver is the resolver for the removeCaregiver field.
func (r *mutationResolver) RemoveCaregiver(ctx context.Context, petID string, caregiverID string) (bool, error) {
	if err := r.PetSvc.RemoveCaregiver(ctx, petID, caregiverID); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// LogLitter is the resolver for the logLitter field.
func (r *mutationResolver) LogLitter(ctx context.Context, petID string, input model.LitterLogInput) (*model.LitterLog, error) {
	l, err := r.PetSvc.CreateLitterLog(ctx, petID, litterInputBody(input))
	if err != nil {
		return nil, gqlErr(err)
	}
	return toLitterLog(*l), nil
}

// LogLitterBatch is the resolver for the logLitterBatch field.
func (r *mutationResolver) LogLitterBatch(ctx context.Context, petID string, inputs []*model.LitterLogInput) ([]*model.LitterLog, error) {
	body := make([]map[string]any, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		body = append(body, litterInputBody(*in))
	}
	logs, err := r.PetSvc.CreateLitterLogBatch(ctx, petID, body)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*model.LitterLog, 0, len(logs))
	for _, l := range logs {
		out = append(out, toLitterLog(l))
	}
	return out, nil
}

// DeleteLitterLog is the resolver for the deleteLitterLog field.
func (r *mutationResolver) DeleteLitterLog(ctx context.Context, petID string, logID string) (bool, error) {
	if err := r.PetSvc.DeleteLitterLog(ctx, petID, logID); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// LogWater is the resolver for the logWater field.
func (r *mutationResolver) LogWater(ctx context.Context, petID string, input model.WaterLogInput) (*model.WaterLog, error) {
	l, err := r.PetSvc.CreateWaterLog(ctx, petID, waterInputBody(input))
	if err != nil {
		return nil, gqlErr(err)
	}
	return toWaterLog(*l), nil
}

// DeleteWaterLog is the resolver for the deleteWaterLog field.
func (r *mutationResolver) DeleteWaterLog(ctx context.Context, petID string, logID string) (bool, error) {
	if err := r.PetSvc.DeleteWaterLog(ctx, petID, logID); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// Admin is the resolver for the admin field.
func (r *mutationResolver) Admin(ctx context.Context) (*model.AdminMutation, error) {
	return &model.AdminMutation{}, nil
}

// AgeLabel is the resolver for the ageLabel field.
func (r *petResolver) AgeLabel(ctx context.Context, obj *model.Pet) (string, error) {
	return ageLabel(obj.BirthDate, time.Now()), nil
}

// Owner is the resolver for the owner field.
func (r *petResolver) Owner(ctx context.Context, obj *model.Pet) (*model.User, error) {
	src, err := r.source(ctx, obj.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	// ownerUsername ถูก denormalize เก็บไว้ตอนสร้าง จึงใช้ได้ทันที
	// โดยไม่ต้องถาม auth-service — และยังใช้ได้แม้ auth-service ล่ม
	u := &model.User{ID: src.OwnerID, FullName: src.OwnerUsername}
	if l := loader.From(ctx); l != nil {
		if full := l.User(ctx, src.OwnerID); full.Email != "" {
			u = toUser(full)
		}
	}
	return u, nil
}

// Caregivers is the resolver for the caregivers field.
func (r *petResolver) Caregivers(ctx context.Context, obj *model.Pet) ([]*model.PetCaregiver, error) {
	src, err := r.source(ctx, obj.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*model.PetCaregiver, 0, len(src.Caregivers))
	for _, c := range src.Caregivers {
		out = append(out, caregiverWithUser(c))
	}
	return out, nil
}

// ViewerPermissions is the resolver for the viewerPermissions field.
func (r *petResolver) ViewerPermissions(ctx context.Context, obj *model.Pet) (*model.PetViewerPermissions, error) {
	src, err := r.source(ctx, obj.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	l := loader.From(ctx)
	if l == nil {
		return nil, internalErr("ไม่มี loader ใน request นี้")
	}
	me, err := l.Me(ctx)
	if err != nil {
		return nil, gqlErr(err)
	}
	return viewerPermissions(src, me.ID, me.Roles), nil
}

// AvatarURL is the resolver for the avatarUrl field.
func (r *petResolver) AvatarURL(ctx context.Context, obj *model.Pet) (*string, error) {
	if !obj.HasAvatar {
		return nil, nil
	}
	// ชี้ไปที่ REST เดิมที่มี ETag อยู่แล้ว ไม่ส่งตัวรูปผ่าน GraphQL
	url := r.Cfg.PublicBaseURL + "/api/v1/pets/" + obj.ID + "/avatar"
	return &url, nil
}

// LitterLogs is the resolver for the litterLogs field.
func (r *petResolver) LitterLogs(ctx context.Context, obj *model.Pet, first *int, after *string, from *time.Time, to *time.Time) (*model.LitterLogConnection, error) {
	size := pageSize(first)
	logs, next, hasMore, err := r.PetSvc.ListLitterLogs(ctx, obj.ID, size, after)
	if err != nil {
		return nil, gqlErr(err)
	}
	logs = filterLitterByRange(logs, from, to)

	edges := make([]*model.LitterLogEdge, 0, len(logs))
	for _, l := range logs {
		edges = append(edges, &model.LitterLogEdge{Cursor: l.ID, Node: toLitterLog(l)})
	}
	return &model.LitterLogConnection{
		Edges: edges,
		// totalCount เป็น null เสมอสำหรับ log — REST ไม่นับให้เพราะแพงเกินไป
		PageInfo: &model.PageInfo{HasNextPage: hasMore, EndCursor: next},
	}, nil
}

// WaterLogs is the resolver for the waterLogs field.
func (r *petResolver) WaterLogs(ctx context.Context, obj *model.Pet, first *int, after *string, from *time.Time, to *time.Time) (*model.WaterLogConnection, error) {
	size := pageSize(first)
	logs, next, hasMore, err := r.PetSvc.ListWaterLogs(ctx, obj.ID, size, after)
	if err != nil {
		return nil, gqlErr(err)
	}
	logs = filterWaterByRange(logs, from, to)

	edges := make([]*model.WaterLogEdge, 0, len(logs))
	for _, l := range logs {
		edges = append(edges, &model.WaterLogEdge{Cursor: l.ID, Node: toWaterLog(l)})
	}
	return &model.WaterLogConnection{
		Edges:    edges,
		PageInfo: &model.PageInfo{HasNextPage: hasMore, EndCursor: next},
	}, nil
}

// LitterSummary is the resolver for the litterSummary field.
func (r *petResolver) LitterSummary(ctx context.Context, obj *model.Pet, from time.Time, to time.Time) (*model.LitterSummary, error) {
	logs, err := r.allLitterInRange(ctx, obj.ID, from, to)
	if err != nil {
		return nil, gqlErr(err)
	}
	return buildLitterSummary(logs, from, to), nil
}

// WaterSummary is the resolver for the waterSummary field.
func (r *petResolver) WaterSummary(ctx context.Context, obj *model.Pet, from time.Time, to time.Time) (*model.WaterSummary, error) {
	logs, err := r.allWaterInRange(ctx, obj.ID, from, to)
	if err != nil {
		return nil, gqlErr(err)
	}
	return buildWaterSummary(logs, from, to, obj.CurrentWeight), nil
}

// User is the resolver for the user field.
func (r *petCaregiverResolver) User(ctx context.Context, obj *model.PetCaregiver) (*model.User, error) {
	if obj.User != nil && obj.User.Email != "" {
		return obj.User, nil
	}
	l := loader.From(ctx)
	if l == nil || obj.User == nil {
		return obj.User, nil
	}
	// ดึงครั้งเดียวต่อ request แล้วใช้ซ้ำ ไม่ว่าจะมีผู้ดูแลกี่คน
	return toUser(l.User(ctx, obj.User.ID)), nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.Viewer, error) {
	l := loader.From(ctx)
	if l == nil {
		return nil, internalErr("ไม่มี loader ใน request นี้")
	}
	me, err := l.Me(ctx)
	if err != nil {
		return nil, gqlErr(err)
	}
	return &model.Viewer{
		ID: me.ID, Email: me.Email, FullName: me.FullName,
		EmailVerified: me.EmailVerified, Roles: toRoles(me.Roles),
	}, nil
}

// Pet is the resolver for the pet field.
func (r *queryResolver) Pet(ctx context.Context, id string) (*model.Pet, error) {
	p, err := r.PetSvc.GetPet(ctx, id)
	if err != nil {
		var ce *client.Error
		if asErr(err, &ce) && (ce.Status == 404 || ce.Status == 403) {
			// schema ประกาศ pet เป็น nullable ไว้แล้ว การคืน null
			// ไม่บอกผู้เรียกว่าสัตว์เลี้ยงตัวนี้มีอยู่จริงแต่ไม่มีสิทธิ์ดู
			return nil, nil
		}
		return nil, gqlErr(err)
	}
	return r.petModel(ctx, *p), nil
}

// Admin is the resolver for the admin field.
func (r *queryResolver) Admin(ctx context.Context) (*model.AdminQuery, error) {
	return &model.AdminQuery{}, nil
}

// Pets is the resolver for the pets field.
func (r *viewerResolver) Pets(ctx context.Context, obj *model.Viewer) ([]*model.Pet, error) {
	pets, err := r.PetSvc.ListPets(ctx)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*model.Pet, 0, len(pets))
	for _, p := range pets {
		out = append(out, r.petModel(ctx, p))
	}
	return out, nil
}

// PetCount is the resolver for the petCount field.
func (r *viewerResolver) PetCount(ctx context.Context, obj *model.Viewer) (int, error) {
	pets, err := r.PetSvc.ListPets(ctx)
	if err != nil {
		return 0, gqlErr(err)
	}
	return len(pets), nil
}

// AdminMutation returns AdminMutationResolver implementation.
func (r *Resolver) AdminMutation() AdminMutationResolver { return &adminMutationResolver{r} }

// AdminQuery returns AdminQueryResolver implementation.
func (r *Resolver) AdminQuery() AdminQueryResolver { return &adminQueryResolver{r} }

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Pet returns PetResolver implementation.
func (r *Resolver) Pet() PetResolver { return &petResolver{r} }

// PetCaregiver returns PetCaregiverResolver implementation.
func (r *Resolver) PetCaregiver() PetCaregiverResolver { return &petCaregiverResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Viewer returns ViewerResolver implementation.
func (r *Resolver) Viewer() ViewerResolver { return &viewerResolver{r} }

type (
	adminMutationResolver struct{ *Resolver }
	adminQueryResolver    struct{ *Resolver }
	eventResolver         struct{ *Resolver }
	mutationResolver      struct{ *Resolver }
	petResolver           struct{ *Resolver }
	petCaregiverResolver  struct{ *Resolver }
	queryResolver         struct{ *Resolver }
	viewerResolver        struct{ *Resolver }
)
